export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const ADDUSER_SUCCESS = "ADDUSER_SUCCESS";
export const ADDUSER_FAIL = "ADDUSER_FAIL";
export const UPDATEUSER_SUCCESS = "UPDATEUSER_SUCCESS";
export const UPDATEUSER_FAIL = "UPDATEUSER_FAIL";
export const DELETEUSER_SUCCESS = "DELETEUSER_SUCCESS";
export const DELETEUSER_FAIL = "DELETEUSER_FAIL";
export const GETALLEUSER_SUCCESS = "GETALLEUSER_SUCCESS";
export const GETALLEUSER_FAIL = "GETALLEUSER_FAIL";
export const GETAEUSER_SUCCESS = "GETAEUSER_SUCCESS";
export const GETAEUSER_FAIL = "GETAEUSER_FAIL";
export const GETALLRESOURCE_SUCCESS = "GETALLRESOURCE_SUCCESS";
export const GETALLRESOURCE_FAIL = "GETALLRESOURCE_FAIL";
export const GETARESOURCE_SUCCESS = "GETARESOURCE_SUCCESS";
export const GETARESOURCE_FAIL = "GETARESOURCE_FAIL";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
